version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/jigglogkotlin
    overwrite: yes
permissions:
  - object: /home/ubuntu/
    patern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  BeforeInstall:
    - location: /home/ubuntu/jigglogkotlin/scripts/before_deploy.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: /home/ubuntu/jigglogkotlin/scripts/after_deploy.sh
      timeout: 300
      runas: ubuntu