#version: 0.0
#os: linux
#
#files:
#  - source: /
#    destination: /home/ubuntu/jigglog
#    overwrite: yes
#permissions:
#  - object: /home/ubuntu/
#    patern: "**"
#    owner: ubuntu
#    group: ubuntu
#    mode: 755
version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy