version: '3.7'
services:
  redis:
    image: redis:alpine
    command: redis-server --port 6379
    container_name: redis
    hostname: redis
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379
    networks:
      - internal-network
  spring-boot:
    container_name: spring-boot
    build: ./
    ports:
      - 8080:8080
    networks:
      - internal-network
    depends_on:
      - redis


networks:
  internal-network:
    driver: bridge