name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

      # Build
    - name: 그래들 빌드
      run: ./gradlew clean build
        
    # Jar 파일 Copy
    - name: Jar 파일 카피
      run: cp ./build/libs/*.jar ./deploy/

    # 압축파일 형태로 전달
    - name: 파일 압축
      run: zip -r -qq -j ./springboot-intro-build.zip ./deploy

    # S3 Bucket으로 copy
    - name: AWS S3로 카피
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: aws s3 cp --region ap-northeast-2 --acl private ./springboot-intro-build.zip s3://jigglog-backend-kotlin/
